FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /rvm
WORKDIR /rvm
RUN gcc -std=gnu99 rcc.c -o rcc

FROM ubuntu:20.04 as package
COPY --from=builder /rvm/rcc /
